### ISSUE TITLE
Napraviti MenuBar

### ISSUE THREAD

**Issue by LukashArts** [AIR-FOI-HR/AIR1913i#16]
- Napraviti dizajn MenuBara.
- Staviti sve stvari s weba da se prikazuju isto i na MenuBaru Android aplikacije.

- [ ] Povezati gumbe iz menija sa pripadajućim ekranima (Projekt, Statistika)

**Comment by tommark214** [comment]
Za menu se koristi DrawerMenu koji sadrži gumb projekti , statistika. U headeru menija nalaze se podaci o korisniku,
