### ISSUE TITLE
Administracija nove funkcionalnosti

### ISSUE THREAD

**Issue by LukashArts** [AIR-FOI-HR/AIR1913i#2]
- [x]  u jednoj rečenici može biti više entiteta (tagom se označava ciljani entitet)
- [x]  svaka rečenica mora imati ID i data (data predstavlja tekst rečenice s tagom)
- [x] download označenih podataka (samo admin ima mogućnost downloada) - JSON export
- [ ] validacija polja u administraciji

**Comment by LukashArts** [comment]
Trenutno je dodano unutar Clienta (/Client/DataImport.aspx) jer se tu učitavaju podaci iz TXT datoteka. 

Više na:
[Dodavanje tekstova u aplikaciju](https://github.com/AIR-FOI-HR/AIR1913i/wiki/U%C4%8Ditavanje-tekstova-u-aplikaciju)

**Comment by tommark214** [comment]
Export projekta u JSON. Za označeni projekt svi njegovi primjeri koji su označeni se exportaju.
